### ISSUE TITLE
RayOutOfMemoryError when running ULTRA experiments

### ISSUE THREAD

**Issue by christianjans** [huawei-noah/SMARTS#557]
### Issue
After running an ULTRA training experiment (this experiment was run with the baseline DQN policy) for about half a day, the program stops because of a RayOutOfMemoryError.

### Error
```sh
2021-02-09 09:09:34,529	ERROR worker.py:987 -- Possible unhandled error from worker: ray::ultra.evaluate.evaluate() (pid=4336, ip=10.208.237.111)
  File "python/ray/_raylet.pyx", line 408, in ray._raylet.execute_task
  File "/SMARTS/.venv/lib/python3.7/site-packages/ray/memory_monitor.py", line 128, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node gpu-machine is used (30.17 / 31.29 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
4331	18.49GiB	ray::__main__.train()
17726	4.02GiB	/SMARTS/.venv/bin/python3.7 /SMARTS/.venv/bin/scl envision start -s ./ultra/scenarios -p 8081
4336	3.29GiB	ray::IDLE
4644	0.22GiB	ray::__main__.train()
4213	0.21GiB	/SMARTS/.venv/bin/python3.7 /SMARTS/.venv/bin/tensorboard --logdir_spec=BDQN:logs/experiment-2021.2.
4274	0.09GiB	python -u ultra/train.py --task 1 --level easy
4325	0.09GiB	ray::IDLE
4335	0.09GiB	ray::IDLE
4334	0.09GiB	ray::IDLE
4330	0.09GiB	ray::IDLE

In addition, up to 0.04 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
---
```
Will send @Gamenot the full log of the program execution internally as I am unable to upload the log to this public post.

### Configuration
Was run in a Docker container with Ubuntu 18.04. `nvidia-smi` outputs:
```sh
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:01:00.0 Off |                  N/A |
| 25%   36C    P2    34W / 215W |    896MiB /  7979MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
The command `$ sumo` outputs:
```sh
Eclipse SUMO sumo Version 1.8.0
 Build features: Linux-4.15.0-124-generic x86_64 GNU 7.5.0 Release Proj GUI SWIG GDAL GL2PS
 Copyright (C) 2001-2020 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.
```
In the virtual environment, `$ pip list` yields the following:
```sh
Package                Version   Location
---------------------- --------- --------
absl-py                0.11.0
aiohttp                3.7.3
apipkg                 1.5
argon2-cffi            20.1.0
astunparse             1.6.3
async-timeout          3.0.1
atari-py               0.2.6
attrs                  20.3.0
Automat                20.2.0
backcall               0.2.0
beautifulsoup4         4.9.3
bleach                 3.2.1
cachetools             4.2.0
certifi                2020.12.5
cffi                   1.14.4
chardet                3.0.4
click                  7.1.2
cloudpickle            1.3.0
colorama               0.4.4
commonmark             0.9.1
constantly             15.1.0
coverage               5.3.1
cycler                 0.10.0
decorator              4.4.2
defusedxml             0.6.0
dill                   0.3.3
dm-tree                0.1.5
entrypoints            0.3
evdev                  1.4.0
execnet                1.7.1
filelock               3.0.12
future                 0.18.2
gast                   0.3.3
gitdb                  4.0.5
GitPython              3.1.12
google                 3.0.0
google-auth            1.24.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.30.0
gym                    0.18.0
h5py                   2.10.0
hyperlink              21.0.0
idna                   2.10
imageio                2.9.0
importlib-metadata     3.4.0
importlib-resources    5.0.0
incremental            17.5.0
iniconfig              1.1.1
ipykernel              5.4.3
ipython                7.19.0
ipython-genutils       0.2.0
jedi                   0.18.0
Jinja2                 2.11.2
joblib                 1.0.0
jsonpatch              1.28
jsonpointer            2.0
jsonschema             3.2.0
jupyter-client         6.1.11
jupyter-core           4.7.0
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
lz4                    3.1.2
Markdown               3.3.3
MarkupSafe             1.1.1
matplotlib             3.3.3
mistune                0.8.4
msgpack                1.0.2
multidict              5.1.0
nbconvert              5.6.1
nbdime                 2.1.0
nbformat               5.1.2
networkx               2.5
notebook               6.2.0
numpy                  1.18.5
oauthlib               3.1.0
opencv-python          4.5.1.48
opencv-python-headless 4.5.1.48
opt-einsum             3.3.0
packaging              20.8
panda3d                1.10.8
panda3d-gltf           0.12
panda3d-simplepbr      0.7
pandas                 1.2.0
pandocfilters          1.4.3
parso                  0.8.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 7.2.0
pip                    20.3.3
pluggy                 0.13.1
prometheus-client      0.9.0
prompt-toolkit         3.0.10
protobuf               3.14.0
psutil                 5.8.0
ptyprocess             0.7.0
py                     1.10.0
py-cpuinfo             7.0.0
py-spy                 0.3.4
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pybullet               3.0.8
pycparser              2.20
pyglet                 1.5.0
Pygments               2.7.4
PyHamcrest             2.0.2
pynput                 1.7.2
pyparsing              2.4.7
pyrsistent             0.17.3
pytest                 6.2.1
pytest-benchmark       3.2.3
pytest-cov             2.11.0
pytest-forked          1.3.0
pytest-notebook        0.6.1
pytest-xdist           2.2.0
python-dateutil        2.8.1
python-xlib            0.29
pytz                   2020.5
PyWavelets             1.1.1
PyYAML                 5.3.1
pyzmq                  21.0.1
ray                    0.8.6
redis                  3.4.1
requests               2.25.1
requests-oauthlib      1.3.0
rich                   9.8.2
rsa                    4.7
Rtree                  0.9.7
scikit-image           0.18.1
scikit-learn           0.24.0
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             47.1.0
sh                     1.14.1
Shapely                1.7.1
six                    1.15.0
sklearn                0.0
smarts                 0.4.11    /SMARTS
smmap                  3.0.4
soupsieve              2.1
supervisor             4.2.1
tableprint             0.9.1
tabulate               0.8.7
tensorboard            2.2.2
tensorboard-plugin-wit 1.7.0
tensorboardX           2.1
tensorflow             2.2.1
tensorflow-estimator   2.2.0
termcolor              1.1.0
terminado              0.9.2
testpath               0.4.4
threadpoolctl          2.1.0
tifffile               2021.1.14
toml                   0.10.2
torch                  1.4.0
torchfile              0.1.0
torchvision            0.5.0
tornado                6.1
traitlets              5.0.5
trimesh                3.9.1
Twisted                20.3.0
typing-extensions      3.7.4.3
urllib3                1.26.2
visdom                 0.1.8.9
wcwidth                0.2.5
webencodings           0.5.1
websocket-client       0.57.0
Werkzeug               1.0.1
wheel                  0.36.2
wrapt                  1.12.1
yarl                   1.6.3
yattag                 1.14.0
zipp                   3.4.0
zope.interface         5.2.0
```

### Steps to Reproduce
- Once the repository is downloaded, SUMO is installed, and the virtual environment is created and activated with the listed packages:
  ```sh
  $ cd SMARTS/
  $ git checkout master  # The current master branch available (latest commit: ebd72d6)
  $ scl scenario build-all ultra/scenarios/pool
  $ python ultra/scenarios/interface.py generate --task 1 --level easy
  $ ./ultra/env/envision_base.sh
  ```
- Then go into ultra/train.py and modify the line:
  ```python
  policy_class = "ultra.baselines.sac:sac-v0"
  ```
  to
  ```python
  policy_class = "ultra.baselines.dqn:dqn-v0"
  ```
- And then finally run the training, redirecting the output to a text file:
  ```sh
  $ ray stop
  $ nohup python -u ultra/train.py --task 1 --level easy > log.txt &
  ```
  View the file with ```$ tail -f log.txt```

### Notes
- I do not encounter this error when running the training in headless mode, i.e. when running `nohup python -u ultra/train.py --task 1 --level easy --headless True > log.txt &`
- I was running the training in the ULTRA Docker container created from the ULTRA Dockerfile, however I anticipate the error will occur independent of Docker?

Let me know what I missed adding or if any other information would be helpful.

**Comment by christianjans** [comment]
### Update
When running training with **SMARTS 0.4.6** I get the same error:
```sh
2021-02-13 00:13:31,651 ERROR worker.py:1012 -- Possible unhandled error from worker: ray::IDLE (pid=27314, ip=10.208.237.111)
  File "python/ray/_raylet.pyx", line 431, in ray._raylet.execute_task
  File "/SMARTS/.venv/lib/python3.7/site-packages/ray/memory_monitor.py", line 120, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node gpu-machine is used (30.58 / 31.29 GB). The top 10 memory consumers are:

PID     MEM     COMMAND
27319   19.28GiB        ray::__main__.train()
17726   3.66GiB /SMARTS/.venv/bin/python3.7 /SMARTS/.venv/bin/scl envision start -s ./ultra/scenarios -p 8081
27314   3.42GiB ray::IDLE
27565   0.21GiB ray::__main__.train()
27269   0.09GiB python -u ultra/train.py --task 1 --level easy
27323   0.08GiB ray::IDLE
27322   0.08GiB ray::IDLE
27320   0.08GiB ray::IDLE
27311   0.08GiB ray::IDLE
27326   0.08GiB ray::IDLE

In addition, up to 0.03 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
---
```
However, when I train with **SMARTS 0.4.12**, the program halts after one of the evaluation rounds.

I will again send @Gamenot the full logs of the programs.

**Comment by JenishPatel99** [comment]
@christianjans By rebooting the remote machine or the native machine will stop all ray processes and the RAM will be freed. The only downside was that you may need to keep restarting if your RAM gets occupied

**Comment by Gamenot** [comment]
@Gamenot @christianjans @JenishPatel99  Look into debugging on the ray side of things `Tip: Use the `ray memory` command to list active objects in the cluster.`

**Comment by Adaickalavan** [comment]
This is a `ray` problem and should be solved on `ray`'s side. Remember that each  `ray:IDLE` process consumes 0.21GB of memory.

Several temporary solutions which I have previoulsy put forth to the ULTRA group:

1) Place a forced garbage collection code at a suitable place in your code, such as within a for loop.
    ```python
    import gc
    import psutil

    def garbage_collect(pct=40.0):
        if psutil.virtual_memory().percent >= pct:
            gc.collect()
        return
    ```

2) Use `ray.shutdown()`.

**Comment by Adaickalavan** [comment]
> @christianjans By rebooting the remote machine or the native machine will stop all ray processes and the RAM will be freed. The only downside was that you may need to keep restarting if your RAM gets occupied

Instead of having to reboot the computer, to kill processes use:
```bash
$ pkill -9 -f ray
$ pkill -9 -f smarts
$ pkill -9 -f python3.7
```

**Comment by Gamenot** [comment]
@christianjans @JenishPatel99 Can you confirm here if this is still a problem for your side?

**Comment by christianjans** [comment]
@Gamenot I will try a long training session tonight, killing all the relevant processes beforehand, and see if the problem still occurs.

**Comment by christianjans** [comment]
Unfortunately the error still occurs with SMARTS 0.4.6.

Did the following commands to run the training:
```sh
(.venv) root@gpu-machine:/SMARTS# pkill -9 -f ray
(.venv) root@gpu-machine:/SMARTS# pkill -9 -f smarts
(.venv) root@gpu-machine:/SMARTS# pkill -9 -f python3.7
(.venv) root@gpu-machine:/SMARTS# ./ultra/env/envision_base.sh
(.venv) root@gpu-machine:/SMARTS# nohup: appending output to 'nohup.out'

(.venv) root@gpu-machine:/SMARTS# ray stop
(.venv) root@gpu-machine:/SMARTS# nvidia-smi
Wed Feb 24 23:15:06 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:01:00.0 Off |                  N/A |
| 25%   24C    P8     6W / 215W |     72MiB /  7979MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
(.venv) root@gpu-machine:/SMARTS# ps -ef | grep ray
root     24414 24249  0 23:15 pts/41   00:00:00 grep --color=auto ray
(.venv) root@gpu-machine:/SMARTS# ps -ef | grep smarts
root     24416 24249  0 23:15 pts/41   00:00:00 grep --color=auto smarts
(.venv) root@gpu-machine:/SMARTS# ps -ef | grep python3.7
root     24288     1  0 23:08 pts/41   00:00:01 /SMARTS/.venv/bin/python3.7 /SMARTS/.venv/bin/scl envision start -s ./ultra/scenarios -p 8081
root     24418 24249  0 23:15 pts/41   00:00:00 grep --color=auto python3.7
(.venv) root@gpu-machine:/SMARTS# nohup python -u ultra/train.py --task 1 --level easy --policy bdqn > log.txt &
[1] 25437
(.venv) root@gpu-machine:/SMARTS# nohup: ignoring input and redirecting stderr to stdout
```
And got the error:
```sh
2021-02-25 10:40:44,769	ERROR worker.py:1012 -- Possible unhandled error from worker: [36mray::IDLE[39m (pid=25489, ip=10.208.237.111)
  File "python/ray/_raylet.pyx", line 431, in ray._raylet.execute_task
  File "/SMARTS/.venv/lib/python3.7/site-packages/ray/memory_monitor.py", line 120, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node gpu-machine is used (30.06 / 31.29 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
25491	20.87GiB	ray::__main__.train()
25489	3.74GiB	ray::IDLE
25323	1.94GiB	/SMARTS/.venv/bin/python3.7 /SMARTS/.venv/bin/scl envision start -s ./ultra/scenarios -p 8081
25733	0.21GiB	ray::__main__.train()
25437	0.09GiB	python -u ultra/train.py --task 1 --level easy --policy dqn
25493	0.08GiB	ray::IDLE
25486	0.08GiB	ray::IDLE
25484	0.08GiB	ray::IDLE
25481	0.08GiB	ray::IDLE
25480	0.08GiB	ray::IDLE

In addition, up to 0.03 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
---
```
Full output sent to @Gamenot.

And after, `ray memory` produced:
```sh
(.venv) root@gpu-machine:/SMARTS# ray memory
Traceback (most recent call last):
  File "/SMARTS/.venv/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/SMARTS/.venv/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1014, in main
    return cli()
  File "/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/SMARTS/.venv/lib/python3.7/site-packages/ray/scripts/scripts.py", line 961, in memory
    address = services.find_redis_address_or_die()
  File "/SMARTS/.venv/lib/python3.7/site-packages/ray/services.py", line 131, in find_redis_address_or_die
    "Could not find any running Ray instance. "
ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.
(.venv) root@gpu-machine:/SMARTS# ps -ef | grep ray
root      7376  7356  0 15:26 pts/43   00:00:00 grep --color=auto ray
root     25733     1  0 Feb24 pts/41   00:00:34 ray::__main__.train()
(.venv) root@gpu-machine:/SMARTS# ps -ef | grep smarts
root      7378  7356  0 15:26 pts/43   00:00:00 grep --color=auto smarts
root     25749 25733  0 Feb24 pts/41   00:00:34 /SMARTS/.venv/bin/python /SMARTS/smarts/zoo/worker.py --port 43019
root     25753 25733  0 Feb24 pts/41   00:00:35 /SMARTS/.venv/bin/python /SMARTS/smarts/zoo/worker.py --port 49471
root     25757 25733  0 Feb24 pts/41   00:00:34 /SMARTS/.venv/bin/python /SMARTS/smarts/zoo/worker.py --port 53889
(.venv) root@gpu-machine:/SMARTS# ps -ef | grep python3.7
root      7380  7356  0 15:27 pts/43   00:00:00 grep --color=auto python3.7
root     25323     1 69 Feb24 pts/41   11:02:49 /SMARTS/.venv/bin/python3.7 /SMARTS/.venv/bin/scl envision start -s ./ultra/scenarios -p 8081
```

**Comment by sah-huawei** [comment]
> @christianjans I am going to attempt a fix using `@ray.remote(max_calls=1)` and running this overnight to see if it works better. I will also try some rough memory profiling to see if I can spot anything.

Hello @christianjans.  Did your investigations lead to any more clues?  Also, I just want to confirm that things work ok with `--headless = True`.  Thanks!

**Comment by christianjans** [comment]
Hi @sah-huawei, I have unfortunately not tried any experiments yet with `@ray.remote(max_calls=1)`. Did @Gamenot have any results with this? And yes, when using SMARTS 0.4.6, running the experiment headless did not produce the error. I have not yet tried this with 0.4.14 (or any other SMARTS version), but if you think it is worthwhile, let me know and I can run an overnight experiment.

**Comment by sah-huawei** [comment]
@ch

> Hi @sah-huawei, I have unfortunately not tried any experiments yet with `@ray.remote(max_calls=1)`. Did @Gamenot have any results with this? And yes, when using SMARTS 0.4.6, running the experiment headless did not produce the error. I have not yet tried this with 0.4.14 (or any other SMARTS version), but if you think it is worthwhile, let me know and I can run an overnight experiment.

@christianjans Thanks for the reply.  Yes, it would be good to know whether it only has issues when running headless.  So yes, if it's not too much trouble, could you please try it overnight?

**Comment by Gamenot** [comment]
> Hi @sah-huawei, I have unfortunately not tried any experiments yet with `@ray.remote(max_calls=1)`. Did @Gamenot have any results with this? 

Yes, I tried it out and the `max_calls=1` seemed to have a positive affect on the memory growth.

**Comment by christianjans** [comment]
Good to hear @Gamenot ! And yes definitely @sah-huawei , sorry I just saw your comment, I will run it tonight.

**Comment by christianjans** [comment]
@sah-huawei, after about 1 day and 15 hours the training ran in headless mode in SMARTS 0.4.14 has not crashed. Running `top` shows:
```sh
Tasks: 557 total,   2 running, 456 sleeping,   0 stopped,   1 zombie
%Cpu(s):  6.2 us,  0.0 sy,  0.0 ni, 87.5 id,  0.0 wa,  0.0 hi,  6.2 si,  0.0 st
KiB Mem : 32808304 total,   766280 free, 21602324 used, 10439700 buff/cache
KiB Swap:  2097148 total,   941404 free,  1155744 used. 10666712 avail Mem
```
After 16 hours there was about 11 GB used, but then I had to run some other experiments that used Ray, and due to Ray not always shutting down after it has been run, this extra 10 GB could have been because of these extra Ray processes.

Note that when running in non-headless mode, the training would crash before (or around) the 16 hour mark however, so there is a difference when running in headless and non-headless mode.

**Comment by sah-huawei** [comment]
> @sah-huawei, after about 1 day and 15 hours the training ran in headless mode in SMARTS 0.4.14 has not crashed. Running `top` shows:
> 
> ```shell
> Tasks: 557 total,   2 running, 456 sleeping,   0 stopped,   1 zombie
> %Cpu(s):  6.2 us,  0.0 sy,  0.0 ni, 87.5 id,  0.0 wa,  0.0 hi,  6.2 si,  0.0 st
> KiB Mem : 32808304 total,   766280 free, 21602324 used, 10439700 buff/cache
> KiB Swap:  2097148 total,   941404 free,  1155744 used. 10666712 avail Mem
> ```
> 
> After 16 hours there was about 11 GB used, but then I had to run some other experiments that used Ray, and due to Ray not always shutting down after it has been run, this extra 10 GB could have been because of these extra Ray processes.
> 
> Note that when running in non-headless mode, the training would crash before (or around) the 16 hour mark however, so there is a difference when running in headless and non-headless mode.

Thanks, @christianjans!  This is helpful information to know.
In the meantime, do you think we should change  the default for Ultra training to use `--headless`? (@Gamenot too)

**Comment by christianjans** [comment]
Glad it could help! Sure, I can bring that up with the ULTRA team.

**Comment by JingfeiPeng** [comment]
when running game of tag demo located at branch `multi_agent_demo` this problem also occurs after traning for a few hours. 

```
Failure # 2 (occurred at 2021-04-04_02-59-01)
Traceback (most recent call last):
  File "/home/kyber/work/SMARTS/.venv/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 854, in _process_trial_save
    checkpoint_value = self.trial_executor.fetch_result(trial)
  File "/home/kyber/work/SMARTS/.venv/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 489, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/kyber/work/SMARTS/.venv/lib/python3.7/site-packages/ray/worker.py", line 1452, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): [36mray::PPO.save()[39m (pid=21682, ip=192.168.3.45)
  File "python/ray/_raylet.pyx", line 444, in ray._raylet.execute_task
  File "/home/kyber/work/SMARTS/.venv/lib/python3.7/site-packages/ray/memory_monitor.py", line 140, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node kyber-Z370 is used (29.75 / 31.29 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
21692	13.08GiB	ray::RolloutWorker
3552	0.78GiB	/usr/lib/firefox/firefox -contentproc -childID 8 -isForBrowser -prefsLen 7902 -prefMapSize 240336 -p
21602	0.59GiB	python examples/game_of_tag/game_of_tag.py scenarios/game_of_tag_simplified_map/
21696	0.48GiB	ray::RolloutWorker
19344	0.43GiB	ray::PPO.train()
21682	0.43GiB	ray::PPO
3130	0.42GiB	/usr/lib/firefox/firefox -new-window
3213	0.37GiB	/usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 1 -prefMapSize 240336 -pare
2840	0.36GiB	/snap/code/60/usr/share/code/code /snap/code/60/usr/share/code/resources/app/out/bootstrap-fork --ty
22257	0.34GiB	ray::RolloutWorker.par_iter_next()

In addition, up to 0.9 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
---
```
However, if I look at my memory, there are plenty of ram available 
![image](https://user-images.githubusercontent.com/36685292/113589148-094a5e80-95ff-11eb-807f-fe3849154f09.png)

When I initially started this training, the headless mode was False, but if I resume the training and turn headless mode to True, the same error still occurs. 
`python examples/game_of_tag/game_of_tag.py scenarios/game_of_tag_simplified_map/ --resume_training`
I will try to restart a training with headless mode to True and `sumo-headless` to false so i can still see the training

also running `ray memory` shows `ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.`

**Comment by JingfeiPeng** [comment]
Update: the out of memory error didn't occurs after restarting a fresh start of the training with `headless=True`, the training had run for more than 10 hours.

**Comment by Yuanzhuo-Liu** [comment]
Hi! @sah-huawei, When I run the PPO in the benchmark, I got the same mistake（ray.memory_monitor.RayOutOfMemoryError）, and I have turn headless true!  May I ask whether this should be solved in ray？

**Comment by Yuanzhuo-Liu** [comment]
![Uploading image.png…]()
Is there any official solution

**Comment by sah-huawei** [comment]
Hi @Yuanzhuo-Liu :  We did find some memory leaks in SMARTS as a result of htis.  See Issues #794 and #805, which led to PR #852.  We also opened issue #870 for more work on this.

I believe PR #852 has only been merged into the `develop` branch so far, but it should be in our next release (0.4.17).
